import request from '../request.ts'

export interface VesselDetail {
    ship_id: number,
    imo: number,
    mmsi: number,
    name_cn: string,
    name_en: string,
    vessel_name_cn: string,
    vessel_name_en: string,
    vessel_type: string,
    vessel_type_name_cn: string,
    vessel_type_name_en: string,
    vessel_type_full_name_cn: string,
    vessel_type_full_name_en: string,
    vessel_sub_type: string,
    vessel_sub_type_name_cn: string,
    vessel_sub_type_name_en: string,
    vessel_sub2_type: string,
    vessel_sub2_type_name_cn: string,
    vessel_sub2_type_name_en: string,
    registry_port: string,
    owner_body: string,
    manage_body: string,
    manage_body_cn: string,
    operator_body: string,
    operator_body_cn: string,
    flag_country: string,
    flag_country_name_cn: string,
    flag_country_name_en: string,
    class_society: string,
    class_society_name_cn: string,
    class_society_name_en: string,
    group_beneficial_owner_country_of_control: string,
    technical_manager_country_of_control: string,
    operator_country_of_control: string,
    main_engine_model: string,
    main_engine_rpm: number,
    main_engine_bore: number,
    main_engine_type: string,
    main_engine_stroke_type: string,
    main_engine_builder: string,
    main_engine_number_of_cylinders: number,
    main_engine_designer: string,
    auxiliary_engine_designer: string,
    auxiliary_engine_builder: string,
    auxiliary_engine_stroke_type: string,
    auxiliary_engines_narrative: string,
    auxiliary_engine_model: string,
    number_of_main_engines: number,
    number_of_auxiliary_engines: number,
    total_kilowatts_of_main_engines: number,
    total_power_of_auxiliary_engines: number,
    total_horse_power_of_main_engines: number,
    build_year: string,
    build_year_month: string,
    oil_tonnes: number,
    height: number,
    length: number,
    width: number,
    sewage_capacity: number,
    draught: number,
    dwt: number,
    cii_rate: number,
    net: number,
    reefer_points: number,
    total_bunker_capacity: number,
    speed: number,
    cii_class: string,
    grt: number,
    number_of_cars: number,
    teu: number,
    passenger_capacity: number,
    gas: number,
    liquid: number,
    retire_year_month: number,
    machinery: string,
    propeller_type: string,
    propeller_manu_facture: string,
    call_sign: string,
    cargo_handling_gear: string,
    boiler_manu_facture: string,
}

export async function queryVesselDetail(mmsi: number) : Promise<{ data: VesselDetail }> {
    return request({
        url: '/api/cosco/vessel/detail',
        method: 'get',
        params: {
            "mmsi": mmsi,
        }
    })
}